import prismadb from "@/lib/prismadb";
import { auth } from "@clerk/nextjs";
import { NextResponse } from "next/server";

export async function POST(req: Request){
  try {
    const { userId } = auth();
    const body = await req.json();

    const { name } = body;

    if(!userId){
      return new NextResponse("Unauthorized", { status: 401 })
    }

    if(!name){
      return new NextResponse("Name is required", { status: 400 })
    }

    const store = await prismadb.store.create({
      data: {
        name,
        userId
      }
    })

    return NextResponse.json(store);
  } catch (error) {
    console.log('[STORES_POST', error);
    return new NextResponse("Internal Server Error", { status: 500})
  }
}

// NOTES
// In the store schema, we have three autogenerated variables, leaving two that we have to update ourselves. They are - userId and name
// The userId is gotten from clerk and the name is gotten from the form we use to create the store
// we have our error message
// We also have the request to create a new store.
